# 项目相关配置
ghc:
  # 名称
  name: jblog-api
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/jblog/uploadPath，Linux配置 /home/jblog/uploadPath）
#  profile: D:/jblog/uploadPath
#  profile: /home/jblog/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30


# 日志配置
logging:
  level:
    com.weiframework: debug
    org.springframework: warn

# Spring配置
spring:
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  profiles: 
    active: dev
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true

    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


##网易系(126/163/yeah)邮箱配置
#  mail:
#    host: smtp.163.com #发送邮件服务器
#    username: shadow13007427338@163.com #发送邮件的邮箱地址
#    password: HGBMDZIGIDSAVAGM #客户端授权码，不是邮箱密码,网易的是自己设置的
#    from: shadow13007427338@163.com # 发送邮件的地址，和上面username一致
#    default-encoding: utf-8
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          required: true

  mail:
    host: smtp.163.com
    username: 13007427338@163.com
    password: HGBMDZIGIDSAVAGM
    default-encoding: UTF-8
    port: 25
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
            fallback: false
          auth: true
          starttls:
            enable: true
            required: true


# token配置
token:
    # 令牌自定义标识
    header: Authorization
    # 令牌秘钥
    secret: abcdefghijklmnopqrstuvwxyz
    # 令牌有效期（默认30分钟）
    expireTime: 30
  
# MyBatis配置
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: com.jblog.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath*:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml
    configuration:
      map-underscore-to-camel-case: true


# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql 

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*
  
# 代码生成
gen: 
  # 作者
  author: jblog
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: com.jblog.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: false
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_
